# Generated by Django 5.0.1 on 2024-01-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=50, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('fam', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('otc', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='coord_id',
        ),
        migrations.RemoveField(
            model_name='images',
            name='pereval_id',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_id',
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень сложности перевала', 'verbose_name_plural': 'Уровни сложности перевала'},
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(default=None, max_length=255, verbose_name='Общее название')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название горы')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Альтернативное название горы')),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новая информация'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.level')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('mount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='base.mount')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.DeleteModel(
            name='Coord',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='Pereval',
        ),
    ]
